// Generated by `npm run db:types` (supabase gen types typescript --local). Do not edit by hand.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  graphql_public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      graphql: {
        Args: {
          extensions?: Json
          operationName?: string
          query?: string
          variables?: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      application_social_accounts: {
        Row: {
          application_id: string
          follower_count: number | null
          handle: string
          platform: Database["public"]["Enums"]["social_platform"]
          profile_url: string
          social_account_id: string
        }
        Insert: {
          application_id: string
          follower_count?: number | null
          handle: string
          platform: Database["public"]["Enums"]["social_platform"]
          profile_url: string
          social_account_id: string
        }
        Update: {
          application_id?: string
          follower_count?: number | null
          handle?: string
          platform?: Database["public"]["Enums"]["social_platform"]
          profile_url?: string
          social_account_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "application_social_accounts_application_id_fkey"
            columns: ["application_id"]
            isOneToOne: false
            referencedRelation: "campaign_applications"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "application_social_accounts_social_account_id_fkey"
            columns: ["social_account_id"]
            isOneToOne: false
            referencedRelation: "social_accounts"
            referencedColumns: ["id"]
          },
        ]
      }
      campaign_application_events: {
        Row: {
          actor_id: string | null
          application_id: string
          created_at: string
          from_status: Database["public"]["Enums"]["application_status"] | null
          id: number
          to_status: Database["public"]["Enums"]["application_status"]
        }
        Insert: {
          actor_id?: string | null
          application_id: string
          created_at?: string
          from_status?: Database["public"]["Enums"]["application_status"] | null
          id?: never
          to_status: Database["public"]["Enums"]["application_status"]
        }
        Update: {
          actor_id?: string | null
          application_id?: string
          created_at?: string
          from_status?: Database["public"]["Enums"]["application_status"] | null
          id?: never
          to_status?: Database["public"]["Enums"]["application_status"]
        }
        Relationships: [
          {
            foreignKeyName: "campaign_application_events_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "campaign_application_events_application_id_fkey"
            columns: ["application_id"]
            isOneToOne: false
            referencedRelation: "campaign_applications"
            referencedColumns: ["id"]
          },
        ]
      }
      campaign_applications: {
        Row: {
          campaign_id: string
          created_at: string
          creator_age: number | null
          creator_categories: string[]
          creator_city: string | null
          creator_country_code: string | null
          creator_gender: Database["public"]["Enums"]["creator_gender"] | null
          creator_id: string
          creator_name: string
          decided_by: string | null
          id: string
          max_follower_count: number | null
          pitch: string | null
          search_text: string
          status: Database["public"]["Enums"]["application_status"]
          status_changed_at: string
        }
        Insert: {
          campaign_id: string
          created_at?: string
          creator_age?: number | null
          creator_categories?: string[]
          creator_city?: string | null
          creator_country_code?: string | null
          creator_gender?: Database["public"]["Enums"]["creator_gender"] | null
          creator_id: string
          creator_name: string
          decided_by?: string | null
          id?: string
          max_follower_count?: number | null
          pitch?: string | null
          search_text: string
          status?: Database["public"]["Enums"]["application_status"]
          status_changed_at?: string
        }
        Update: {
          campaign_id?: string
          created_at?: string
          creator_age?: number | null
          creator_categories?: string[]
          creator_city?: string | null
          creator_country_code?: string | null
          creator_gender?: Database["public"]["Enums"]["creator_gender"] | null
          creator_id?: string
          creator_name?: string
          decided_by?: string | null
          id?: string
          max_follower_count?: number | null
          pitch?: string | null
          search_text?: string
          status?: Database["public"]["Enums"]["application_status"]
          status_changed_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "campaign_applications_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "campaigns"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "campaign_applications_creator_id_fkey"
            columns: ["creator_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "campaign_applications_decided_by_fkey"
            columns: ["decided_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      campaign_assignments: {
        Row: {
          application_id: string
          attempt_count: number
          campaign_id: string
          created_at: string
          creator_id: string
          decided_at: string | null
          due_at: string
          id: string
          max_attempts: number
          reward_cents: number
          status: Database["public"]["Enums"]["assignment_status"]
          submitted_at: string | null
          updated_at: string
        }
        Insert: {
          application_id: string
          attempt_count?: number
          campaign_id: string
          created_at?: string
          creator_id: string
          decided_at?: string | null
          due_at: string
          id?: string
          max_attempts?: number
          reward_cents: number
          status?: Database["public"]["Enums"]["assignment_status"]
          submitted_at?: string | null
          updated_at?: string
        }
        Update: {
          application_id?: string
          attempt_count?: number
          campaign_id?: string
          created_at?: string
          creator_id?: string
          decided_at?: string | null
          due_at?: string
          id?: string
          max_attempts?: number
          reward_cents?: number
          status?: Database["public"]["Enums"]["assignment_status"]
          submitted_at?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "campaign_assignments_application_id_fkey"
            columns: ["application_id"]
            isOneToOne: true
            referencedRelation: "campaign_applications"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "campaign_assignments_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "campaigns"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "campaign_assignments_creator_id_fkey"
            columns: ["creator_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      campaign_creator_categories: {
        Row: {
          campaign_id: string
          category_slug: string
        }
        Insert: {
          campaign_id: string
          category_slug: string
        }
        Update: {
          campaign_id?: string
          category_slug?: string
        }
        Relationships: [
          {
            foreignKeyName: "campaign_creator_categories_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "campaigns"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "campaign_creator_categories_category_slug_fkey"
            columns: ["category_slug"]
            isOneToOne: false
            referencedRelation: "creator_categories"
            referencedColumns: ["slug"]
          },
        ]
      }
      campaign_funding: {
        Row: {
          campaign_id: string
          created_at: string
          creator_budget_cents: number
          creators_required: number
          currency: string
          id: string
          ledger_transaction_id: string
          payer_id: string
          payment_per_creator_cents: number
          platform_fee_bps: number
          platform_fee_cents: number
          status: Database["public"]["Enums"]["campaign_funding_status"]
          total_cents: number
          wallet_account_id: string
        }
        Insert: {
          campaign_id: string
          created_at?: string
          creator_budget_cents: number
          creators_required: number
          currency?: string
          id?: string
          ledger_transaction_id: string
          payer_id: string
          payment_per_creator_cents: number
          platform_fee_bps: number
          platform_fee_cents: number
          status?: Database["public"]["Enums"]["campaign_funding_status"]
          total_cents: number
          wallet_account_id: string
        }
        Update: {
          campaign_id?: string
          created_at?: string
          creator_budget_cents?: number
          creators_required?: number
          currency?: string
          id?: string
          ledger_transaction_id?: string
          payer_id?: string
          payment_per_creator_cents?: number
          platform_fee_bps?: number
          platform_fee_cents?: number
          status?: Database["public"]["Enums"]["campaign_funding_status"]
          total_cents?: number
          wallet_account_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "campaign_funding_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: true
            referencedRelation: "campaigns"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "campaign_funding_ledger_transaction_id_fkey"
            columns: ["ledger_transaction_id"]
            isOneToOne: true
            referencedRelation: "ledger_transactions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "campaign_funding_payer_id_fkey"
            columns: ["payer_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "campaign_funding_wallet_account_id_fkey"
            columns: ["wallet_account_id"]
            isOneToOne: false
            referencedRelation: "wallet_account_balances"
            referencedColumns: ["account_id"]
          },
          {
            foreignKeyName: "campaign_funding_wallet_account_id_fkey"
            columns: ["wallet_account_id"]
            isOneToOne: false
            referencedRelation: "wallet_accounts"
            referencedColumns: ["id"]
          },
        ]
      }
      campaign_locations: {
        Row: {
          campaign_id: string
          city: string | null
          country_code: string
          id: string
          region: string | null
        }
        Insert: {
          campaign_id: string
          city?: string | null
          country_code: string
          id?: string
          region?: string | null
        }
        Update: {
          campaign_id?: string
          city?: string | null
          country_code?: string
          id?: string
          region?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "campaign_locations_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "campaigns"
            referencedColumns: ["id"]
          },
        ]
      }
      campaign_platforms: {
        Row: {
          campaign_id: string
          platform: Database["public"]["Enums"]["social_platform"]
        }
        Insert: {
          campaign_id: string
          platform: Database["public"]["Enums"]["social_platform"]
        }
        Update: {
          campaign_id?: string
          platform?: Database["public"]["Enums"]["social_platform"]
        }
        Relationships: [
          {
            foreignKeyName: "campaign_platforms_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "campaigns"
            referencedColumns: ["id"]
          },
        ]
      }
      campaign_requirements: {
        Row: {
          age_max: number | null
          age_min: number | null
          campaign_id: string
          genders: Database["public"]["Enums"]["creator_gender"][]
          min_followers: number | null
        }
        Insert: {
          age_max?: number | null
          age_min?: number | null
          campaign_id: string
          genders?: Database["public"]["Enums"]["creator_gender"][]
          min_followers?: number | null
        }
        Update: {
          age_max?: number | null
          age_min?: number | null
          campaign_id?: string
          genders?: Database["public"]["Enums"]["creator_gender"][]
          min_followers?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "campaign_requirements_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: true
            referencedRelation: "campaigns"
            referencedColumns: ["id"]
          },
        ]
      }
      campaign_status_events: {
        Row: {
          actor_id: string | null
          campaign_id: string
          created_at: string
          from_status: Database["public"]["Enums"]["campaign_status"] | null
          id: number
          to_status: Database["public"]["Enums"]["campaign_status"]
        }
        Insert: {
          actor_id?: string | null
          campaign_id: string
          created_at?: string
          from_status?: Database["public"]["Enums"]["campaign_status"] | null
          id?: never
          to_status: Database["public"]["Enums"]["campaign_status"]
        }
        Update: {
          actor_id?: string | null
          campaign_id?: string
          created_at?: string
          from_status?: Database["public"]["Enums"]["campaign_status"] | null
          id?: never
          to_status?: Database["public"]["Enums"]["campaign_status"]
        }
        Relationships: [
          {
            foreignKeyName: "campaign_status_events_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "campaign_status_events_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "campaigns"
            referencedColumns: ["id"]
          },
        ]
      }
      campaign_task_type_rules: {
        Row: {
          platform: Database["public"]["Enums"]["social_platform"] | null
          proof_url: Database["public"]["Enums"]["proof_url_requirement"]
          requires_comment_text: boolean
          task_type: Database["public"]["Enums"]["campaign_task_type"]
        }
        Insert: {
          platform?: Database["public"]["Enums"]["social_platform"] | null
          proof_url: Database["public"]["Enums"]["proof_url_requirement"]
          requires_comment_text?: boolean
          task_type: Database["public"]["Enums"]["campaign_task_type"]
        }
        Update: {
          platform?: Database["public"]["Enums"]["social_platform"] | null
          proof_url?: Database["public"]["Enums"]["proof_url_requirement"]
          requires_comment_text?: boolean
          task_type?: Database["public"]["Enums"]["campaign_task_type"]
        }
        Relationships: []
      }
      campaign_tasks: {
        Row: {
          campaign_id: string
          created_at: string
          custom_description: string | null
          id: string
          platform: Database["public"]["Enums"]["social_platform"]
          position: number
          quantity: number
          task_type: Database["public"]["Enums"]["campaign_task_type"]
        }
        Insert: {
          campaign_id: string
          created_at?: string
          custom_description?: string | null
          id?: string
          platform: Database["public"]["Enums"]["social_platform"]
          position?: number
          quantity?: number
          task_type: Database["public"]["Enums"]["campaign_task_type"]
        }
        Update: {
          campaign_id?: string
          created_at?: string
          custom_description?: string | null
          id?: string
          platform?: Database["public"]["Enums"]["social_platform"]
          position?: number
          quantity?: number
          task_type?: Database["public"]["Enums"]["campaign_task_type"]
        }
        Relationships: [
          {
            foreignKeyName: "campaign_tasks_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "campaigns"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "campaign_tasks_campaign_id_platform_fkey"
            columns: ["campaign_id", "platform"]
            isOneToOne: false
            referencedRelation: "campaign_platforms"
            referencedColumns: ["campaign_id", "platform"]
          },
        ]
      }
      campaigns: {
        Row: {
          application_deadline: string | null
          campaign_type: Database["public"]["Enums"]["campaign_type"] | null
          cancellation_reason: string | null
          cancelled_at: string | null
          caption_instructions: string | null
          category_slug: string | null
          created_at: string
          creators_required: number | null
          currency: string
          description: string | null
          funding_requested_at: string | null
          hashtags: string[]
          id: string
          instructions: string | null
          mentions: string[]
          owner_id: string
          payment_per_creator_cents: number | null
          published_at: string | null
          reference_url: string | null
          status: Database["public"]["Enums"]["campaign_status"]
          task_deadline: string | null
          title: string
          updated_at: string
        }
        Insert: {
          application_deadline?: string | null
          campaign_type?: Database["public"]["Enums"]["campaign_type"] | null
          cancellation_reason?: string | null
          cancelled_at?: string | null
          caption_instructions?: string | null
          category_slug?: string | null
          created_at?: string
          creators_required?: number | null
          currency?: string
          description?: string | null
          funding_requested_at?: string | null
          hashtags?: string[]
          id?: string
          instructions?: string | null
          mentions?: string[]
          owner_id?: string
          payment_per_creator_cents?: number | null
          published_at?: string | null
          reference_url?: string | null
          status?: Database["public"]["Enums"]["campaign_status"]
          task_deadline?: string | null
          title: string
          updated_at?: string
        }
        Update: {
          application_deadline?: string | null
          campaign_type?: Database["public"]["Enums"]["campaign_type"] | null
          cancellation_reason?: string | null
          cancelled_at?: string | null
          caption_instructions?: string | null
          category_slug?: string | null
          created_at?: string
          creators_required?: number | null
          currency?: string
          description?: string | null
          funding_requested_at?: string | null
          hashtags?: string[]
          id?: string
          instructions?: string | null
          mentions?: string[]
          owner_id?: string
          payment_per_creator_cents?: number | null
          published_at?: string | null
          reference_url?: string | null
          status?: Database["public"]["Enums"]["campaign_status"]
          task_deadline?: string | null
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "campaigns_category_slug_fkey"
            columns: ["category_slug"]
            isOneToOne: false
            referencedRelation: "creator_categories"
            referencedColumns: ["slug"]
          },
          {
            foreignKeyName: "campaigns_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      creator_categories: {
        Row: {
          label: string
          slug: string
          sort_order: number
        }
        Insert: {
          label: string
          slug: string
          sort_order?: number
        }
        Update: {
          label?: string
          slug?: string
          sort_order?: number
        }
        Relationships: []
      }
      creator_profile_categories: {
        Row: {
          category_slug: string
          user_id: string
        }
        Insert: {
          category_slug: string
          user_id: string
        }
        Update: {
          category_slug?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "creator_profile_categories_category_slug_fkey"
            columns: ["category_slug"]
            isOneToOne: false
            referencedRelation: "creator_categories"
            referencedColumns: ["slug"]
          },
          {
            foreignKeyName: "creator_profile_categories_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "creator_profiles"
            referencedColumns: ["user_id"]
          },
        ]
      }
      creator_profiles: {
        Row: {
          country_code: string | null
          created_at: string
          date_of_birth: string | null
          gender: Database["public"]["Enums"]["creator_gender"] | null
          updated_at: string
          user_id: string
        }
        Insert: {
          country_code?: string | null
          created_at?: string
          date_of_birth?: string | null
          gender?: Database["public"]["Enums"]["creator_gender"] | null
          updated_at?: string
          user_id: string
        }
        Update: {
          country_code?: string | null
          created_at?: string
          date_of_birth?: string | null
          gender?: Database["public"]["Enums"]["creator_gender"] | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "creator_profiles_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      ledger_transactions: {
        Row: {
          campaign_id: string | null
          created_at: string
          description: string
          id: string
          idempotency_key: string
          initiated_by: string
          is_test: boolean
          kind: Database["public"]["Enums"]["ledger_transaction_kind"]
          payment_transaction_id: string | null
        }
        Insert: {
          campaign_id?: string | null
          created_at?: string
          description: string
          id?: string
          idempotency_key: string
          initiated_by: string
          is_test?: boolean
          kind: Database["public"]["Enums"]["ledger_transaction_kind"]
          payment_transaction_id?: string | null
        }
        Update: {
          campaign_id?: string | null
          created_at?: string
          description?: string
          id?: string
          idempotency_key?: string
          initiated_by?: string
          is_test?: boolean
          kind?: Database["public"]["Enums"]["ledger_transaction_kind"]
          payment_transaction_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "ledger_transactions_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "campaigns"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ledger_transactions_initiated_by_fkey"
            columns: ["initiated_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ledger_transactions_payment_transaction_id_fkey"
            columns: ["payment_transaction_id"]
            isOneToOne: true
            referencedRelation: "payment_transactions"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          body: string
          created_at: string
          data: Json
          email_status: Database["public"]["Enums"]["notification_email_status"]
          id: string
          link_path: string | null
          read_at: string | null
          recipient_id: string
          title: string
          type: Database["public"]["Enums"]["notification_type"]
        }
        Insert: {
          body: string
          created_at?: string
          data?: Json
          email_status?: Database["public"]["Enums"]["notification_email_status"]
          id?: string
          link_path?: string | null
          read_at?: string | null
          recipient_id: string
          title: string
          type: Database["public"]["Enums"]["notification_type"]
        }
        Update: {
          body?: string
          created_at?: string
          data?: Json
          email_status?: Database["public"]["Enums"]["notification_email_status"]
          id?: string
          link_path?: string | null
          read_at?: string | null
          recipient_id?: string
          title?: string
          type?: Database["public"]["Enums"]["notification_type"]
        }
        Relationships: [
          {
            foreignKeyName: "notifications_recipient_id_fkey"
            columns: ["recipient_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      payment_transactions: {
        Row: {
          amount_cents: number
          completed_at: string | null
          created_at: string
          currency: string
          direction: string
          failure_reason: string | null
          id: string
          idempotency_key: string
          is_test: boolean
          provider: string
          provider_reference: string
          status: Database["public"]["Enums"]["payment_transaction_status"]
          user_id: string
          wallet_account_id: string
        }
        Insert: {
          amount_cents: number
          completed_at?: string | null
          created_at?: string
          currency?: string
          direction?: string
          failure_reason?: string | null
          id?: string
          idempotency_key: string
          is_test: boolean
          provider: string
          provider_reference: string
          status: Database["public"]["Enums"]["payment_transaction_status"]
          user_id: string
          wallet_account_id: string
        }
        Update: {
          amount_cents?: number
          completed_at?: string | null
          created_at?: string
          currency?: string
          direction?: string
          failure_reason?: string | null
          id?: string
          idempotency_key?: string
          is_test?: boolean
          provider?: string
          provider_reference?: string
          status?: Database["public"]["Enums"]["payment_transaction_status"]
          user_id?: string
          wallet_account_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "payment_transactions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "payment_transactions_wallet_account_id_fkey"
            columns: ["wallet_account_id"]
            isOneToOne: false
            referencedRelation: "wallet_account_balances"
            referencedColumns: ["account_id"]
          },
          {
            foreignKeyName: "payment_transactions_wallet_account_id_fkey"
            columns: ["wallet_account_id"]
            isOneToOne: false
            referencedRelation: "wallet_accounts"
            referencedColumns: ["id"]
          },
        ]
      }
      platform_settings: {
        Row: {
          id: boolean
          test_funds_enabled: boolean
          updated_at: string
        }
        Insert: {
          id?: boolean
          test_funds_enabled?: boolean
          updated_at?: string
        }
        Update: {
          id?: boolean
          test_funds_enabled?: boolean
          updated_at?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          active_workspace: Database["public"]["Enums"]["workspace_role"]
          avatar_path: string | null
          bio: string | null
          city: string | null
          created_at: string
          full_name: string
          id: string
          onboarding_completed_at: string | null
          phone: string | null
          updated_at: string
          workspace_chosen_at: string | null
        }
        Insert: {
          active_workspace?: Database["public"]["Enums"]["workspace_role"]
          avatar_path?: string | null
          bio?: string | null
          city?: string | null
          created_at?: string
          full_name?: string
          id: string
          onboarding_completed_at?: string | null
          phone?: string | null
          updated_at?: string
          workspace_chosen_at?: string | null
        }
        Update: {
          active_workspace?: Database["public"]["Enums"]["workspace_role"]
          avatar_path?: string | null
          bio?: string | null
          city?: string | null
          created_at?: string
          full_name?: string
          id?: string
          onboarding_completed_at?: string | null
          phone?: string | null
          updated_at?: string
          workspace_chosen_at?: string | null
        }
        Relationships: []
      }
      social_accounts: {
        Row: {
          connection_method: Database["public"]["Enums"]["social_connection_method"]
          created_at: string
          disconnected_at: string | null
          follower_count: number | null
          handle: string
          id: string
          platform: Database["public"]["Enums"]["social_platform"]
          provider_account_id: string | null
          status: Database["public"]["Enums"]["social_account_status"]
          updated_at: string
          user_id: string
          verification_status: Database["public"]["Enums"]["social_verification_status"]
        }
        Insert: {
          connection_method?: Database["public"]["Enums"]["social_connection_method"]
          created_at?: string
          disconnected_at?: string | null
          follower_count?: number | null
          handle: string
          id?: string
          platform: Database["public"]["Enums"]["social_platform"]
          provider_account_id?: string | null
          status?: Database["public"]["Enums"]["social_account_status"]
          updated_at?: string
          user_id?: string
          verification_status?: Database["public"]["Enums"]["social_verification_status"]
        }
        Update: {
          connection_method?: Database["public"]["Enums"]["social_connection_method"]
          created_at?: string
          disconnected_at?: string | null
          follower_count?: number | null
          handle?: string
          id?: string
          platform?: Database["public"]["Enums"]["social_platform"]
          provider_account_id?: string | null
          status?: Database["public"]["Enums"]["social_account_status"]
          updated_at?: string
          user_id?: string
          verification_status?: Database["public"]["Enums"]["social_verification_status"]
        }
        Relationships: [
          {
            foreignKeyName: "social_accounts_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      task_reviews: {
        Row: {
          allow_resubmission: boolean
          created_at: string
          decision: Database["public"]["Enums"]["review_decision"]
          id: string
          reason: string | null
          reviewer_id: string
          submission_id: string
        }
        Insert: {
          allow_resubmission?: boolean
          created_at?: string
          decision: Database["public"]["Enums"]["review_decision"]
          id?: string
          reason?: string | null
          reviewer_id: string
          submission_id: string
        }
        Update: {
          allow_resubmission?: boolean
          created_at?: string
          decision?: Database["public"]["Enums"]["review_decision"]
          id?: string
          reason?: string | null
          reviewer_id?: string
          submission_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "task_reviews_reviewer_id_fkey"
            columns: ["reviewer_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_reviews_submission_id_fkey"
            columns: ["submission_id"]
            isOneToOne: true
            referencedRelation: "task_submissions"
            referencedColumns: ["id"]
          },
        ]
      }
      task_submission_items: {
        Row: {
          campaign_task_id: string
          comment_text: string | null
          proof_url: string | null
          submission_id: string
        }
        Insert: {
          campaign_task_id: string
          comment_text?: string | null
          proof_url?: string | null
          submission_id: string
        }
        Update: {
          campaign_task_id?: string
          comment_text?: string | null
          proof_url?: string | null
          submission_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "task_submission_items_campaign_task_id_fkey"
            columns: ["campaign_task_id"]
            isOneToOne: false
            referencedRelation: "campaign_tasks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_submission_items_submission_id_fkey"
            columns: ["submission_id"]
            isOneToOne: false
            referencedRelation: "task_submissions"
            referencedColumns: ["id"]
          },
        ]
      }
      task_submissions: {
        Row: {
          assignment_id: string
          attempt: number
          id: string
          note: string | null
          submitted_at: string
        }
        Insert: {
          assignment_id: string
          attempt: number
          id?: string
          note?: string | null
          submitted_at?: string
        }
        Update: {
          assignment_id?: string
          attempt?: number
          id?: string
          note?: string | null
          submitted_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "task_submissions_assignment_id_fkey"
            columns: ["assignment_id"]
            isOneToOne: false
            referencedRelation: "campaign_assignments"
            referencedColumns: ["id"]
          },
        ]
      }
      user_roles: {
        Row: {
          granted_at: string
          granted_by: string | null
          role: Database["public"]["Enums"]["platform_role"]
          user_id: string
        }
        Insert: {
          granted_at?: string
          granted_by?: string | null
          role: Database["public"]["Enums"]["platform_role"]
          user_id: string
        }
        Update: {
          granted_at?: string
          granted_by?: string | null
          role?: Database["public"]["Enums"]["platform_role"]
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_roles_granted_by_fkey"
            columns: ["granted_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_roles_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      wallet_accounts: {
        Row: {
          campaign_id: string | null
          created_at: string
          currency: string
          id: string
          kind: Database["public"]["Enums"]["wallet_account_kind"]
          owner_id: string | null
          provider: string | null
        }
        Insert: {
          campaign_id?: string | null
          created_at?: string
          currency?: string
          id?: string
          kind: Database["public"]["Enums"]["wallet_account_kind"]
          owner_id?: string | null
          provider?: string | null
        }
        Update: {
          campaign_id?: string | null
          created_at?: string
          currency?: string
          id?: string
          kind?: Database["public"]["Enums"]["wallet_account_kind"]
          owner_id?: string | null
          provider?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "wallet_accounts_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "campaigns"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "wallet_accounts_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      wallet_ledger_entries: {
        Row: {
          account_id: string
          amount_cents: number
          created_at: string
          currency: string
          entry_type: Database["public"]["Enums"]["ledger_entry_type"]
          id: number
          transaction_id: string
        }
        Insert: {
          account_id: string
          amount_cents: number
          created_at?: string
          currency?: string
          entry_type: Database["public"]["Enums"]["ledger_entry_type"]
          id?: never
          transaction_id: string
        }
        Update: {
          account_id?: string
          amount_cents?: number
          created_at?: string
          currency?: string
          entry_type?: Database["public"]["Enums"]["ledger_entry_type"]
          id?: never
          transaction_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "wallet_ledger_entries_account_id_fkey"
            columns: ["account_id"]
            isOneToOne: false
            referencedRelation: "wallet_account_balances"
            referencedColumns: ["account_id"]
          },
          {
            foreignKeyName: "wallet_ledger_entries_account_id_fkey"
            columns: ["account_id"]
            isOneToOne: false
            referencedRelation: "wallet_accounts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "wallet_ledger_entries_transaction_id_fkey"
            columns: ["transaction_id"]
            isOneToOne: false
            referencedRelation: "ledger_transactions"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      wallet_account_balances: {
        Row: {
          account_id: string | null
          balance_cents: number | null
          campaign_id: string | null
          currency: string | null
          kind: Database["public"]["Enums"]["wallet_account_kind"] | null
          owner_id: string | null
        }
        Relationships: [
          {
            foreignKeyName: "wallet_accounts_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "campaigns"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "wallet_accounts_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      wallet_statement: {
        Row: {
          account_id: string | null
          amount_cents: number | null
          balance_after_cents: number | null
          campaign_id: string | null
          created_at: string | null
          description: string | null
          entry_type: Database["public"]["Enums"]["ledger_entry_type"] | null
          id: number | null
          is_test: boolean | null
          owner_id: string | null
          transaction_kind:
            | Database["public"]["Enums"]["ledger_transaction_kind"]
            | null
        }
        Relationships: [
          {
            foreignKeyName: "ledger_transactions_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "campaigns"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "wallet_accounts_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "wallet_ledger_entries_account_id_fkey"
            columns: ["account_id"]
            isOneToOne: false
            referencedRelation: "wallet_account_balances"
            referencedColumns: ["account_id"]
          },
          {
            foreignKeyName: "wallet_ledger_entries_account_id_fkey"
            columns: ["account_id"]
            isOneToOne: false
            referencedRelation: "wallet_accounts"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Functions: {
      _account_balance: { Args: { _account_id: string }; Returns: number }
      _assert_campaign_fundable: {
        Args: { _campaign_id: string }
        Returns: undefined
      }
      _campaign_eligibility_issues: {
        Args: { _campaign_id: string; _user_id: string }
        Returns: {
          code: string
          platform: Database["public"]["Enums"]["social_platform"]
        }[]
      }
      _ensure_user_wallet: { Args: { _user_id: string }; Returns: string }
      _notify: {
        Args: {
          _body: string
          _data?: Json
          _link: string
          _recipient: string
          _title: string
          _type: Database["public"]["Enums"]["notification_type"]
        }
        Returns: undefined
      }
      _sync_campaign_review_state: {
        Args: { _campaign_id: string }
        Returns: undefined
      }
      _system_account: {
        Args: {
          _campaign_id?: string
          _kind: Database["public"]["Enums"]["wallet_account_kind"]
          _provider?: string
        }
        Returns: string
      }
      application_transition_allowed: {
        Args: {
          _from: Database["public"]["Enums"]["application_status"]
          _to: Database["public"]["Enums"]["application_status"]
        }
        Returns: boolean
      }
      apply_to_campaign: {
        Args: { p_campaign_id: string; p_pitch?: string }
        Returns: string
      }
      campaign_advertiser_name: {
        Args: { p_campaign_id: string }
        Returns: string
      }
      campaign_application_counts: {
        Args: { p_campaign_id: string }
        Returns: {
          status: Database["public"]["Enums"]["application_status"]
          total: number
        }[]
      }
      campaign_assignment_counts: {
        Args: { p_campaign_id: string }
        Returns: {
          status: Database["public"]["Enums"]["assignment_status"]
          total: number
        }[]
      }
      campaign_is_editable: {
        Args: { _status: Database["public"]["Enums"]["campaign_status"] }
        Returns: boolean
      }
      campaign_transition_allowed: {
        Args: {
          _from: Database["public"]["Enums"]["campaign_status"]
          _to: Database["public"]["Enums"]["campaign_status"]
        }
        Returns: boolean
      }
      can_edit_campaign: { Args: { _campaign_id: string }; Returns: boolean }
      can_view_application: {
        Args: { _application_id: string }
        Returns: boolean
      }
      can_view_assignment: {
        Args: { _assignment_id: string }
        Returns: boolean
      }
      can_view_campaign: { Args: { _campaign_id: string }; Returns: boolean }
      can_view_submission: {
        Args: { _submission_id: string }
        Returns: boolean
      }
      cancel_campaign: {
        Args: { p_campaign_id: string; p_reason?: string }
        Returns: Database["public"]["Enums"]["campaign_status"]
      }
      close_campaign_applications: {
        Args: { p_campaign_id: string }
        Returns: Database["public"]["Enums"]["campaign_status"]
      }
      complete_campaign: {
        Args: { p_campaign_id: string }
        Returns: Database["public"]["Enums"]["campaign_status"]
      }
      decide_application: {
        Args: { p_action: string; p_application_id: string }
        Returns: Database["public"]["Enums"]["application_status"]
      }
      discover_campaigns: {
        Args: {
          p_category?: string
          p_eligible_only?: boolean
          p_limit?: number
          p_offset?: number
          p_platform?: Database["public"]["Enums"]["social_platform"]
          p_search?: string
          p_sort?: string
        }
        Returns: {
          advertiser_name: string
          application_deadline: string
          applied: boolean
          campaign_type: Database["public"]["Enums"]["campaign_type"]
          category_slug: string
          creators_required: number
          description: string
          id: string
          issues: string[]
          min_followers: number
          payment_per_creator_cents: number
          platforms: Database["public"]["Enums"]["social_platform"][]
          task_deadline: string
          task_types: Database["public"]["Enums"]["campaign_task_type"][]
          title: string
          total_count: number
        }[]
      }
      fund_and_publish_campaign: {
        Args: { p_campaign_id: string; p_idempotency_key: string }
        Returns: {
          already_funded: boolean
          campaign_status: Database["public"]["Enums"]["campaign_status"]
          funding_id: string
          total_cents: number
        }[]
      }
      has_applied_to_campaign: {
        Args: { _campaign_id: string }
        Returns: boolean
      }
      has_platform_role: {
        Args: { _role: Database["public"]["Enums"]["platform_role"] }
        Returns: boolean
      }
      is_admin: { Args: never; Returns: boolean }
      is_campaign_owner: { Args: { _campaign_id: string }; Returns: boolean }
      mark_notifications_read: { Args: { p_ids?: string[] }; Returns: number }
      my_campaign_eligibility: {
        Args: { p_campaign_id: string }
        Returns: {
          code: string
          platform: Database["public"]["Enums"]["social_platform"]
        }[]
      }
      my_campaign_status_counts: {
        Args: never
        Returns: {
          status: Database["public"]["Enums"]["campaign_status"]
          total: number
        }[]
      }
      platform_fee_bps: { Args: never; Returns: number }
      platform_fee_cents: {
        Args: { _creator_budget_cents: number }
        Returns: number
      }
      proof_url_matches_platform: {
        Args: {
          _platform: Database["public"]["Enums"]["social_platform"]
          _url: string
        }
        Returns: boolean
      }
      record_test_deposit: {
        Args: {
          p_amount_cents: number
          p_currency: string
          p_failure_reason?: string
          p_idempotency_key: string
          p_provider_reference: string
          p_status: Database["public"]["Enums"]["payment_transaction_status"]
        }
        Returns: {
          payment_transaction_id: string
          replayed: boolean
          status: Database["public"]["Enums"]["payment_transaction_status"]
        }[]
      }
      request_campaign_funding: {
        Args: { p_campaign_id: string }
        Returns: Database["public"]["Enums"]["campaign_status"]
      }
      review_task_submission: {
        Args: {
          p_allow_resubmission?: boolean
          p_decision: Database["public"]["Enums"]["review_decision"]
          p_reason?: string
          p_submission_id: string
        }
        Returns: Database["public"]["Enums"]["assignment_status"]
      }
      save_campaign_draft: {
        Args: {
          p_campaign: Json
          p_campaign_id?: string
          p_categories: string[]
          p_locations: Json
          p_platforms: Database["public"]["Enums"]["social_platform"][]
          p_requirements?: Json
          p_tasks: Json
        }
        Returns: string
      }
      save_creator_profile: {
        Args: {
          p_categories?: string[]
          p_country_code?: string
          p_date_of_birth?: string
          p_gender?: Database["public"]["Enums"]["creator_gender"]
        }
        Returns: undefined
      }
      social_profile_url: {
        Args: {
          _handle: string
          _platform: Database["public"]["Enums"]["social_platform"]
        }
        Returns: string
      }
      start_campaign_work: {
        Args: { p_campaign_id: string }
        Returns: Database["public"]["Enums"]["campaign_status"]
      }
      submit_task_completion: {
        Args: { p_assignment_id: string; p_items: Json; p_note?: string }
        Returns: string
      }
    }
    Enums: {
      application_status: "pending" | "shortlisted" | "selected" | "rejected"
      assignment_status:
        | "in_progress"
        | "submitted"
        | "revision_requested"
        | "approved"
        | "rejected"
        | "expired"
        | "payout_pending"
        | "paid"
      campaign_funding_status: "succeeded"
      campaign_status:
        | "draft"
        | "funding_required"
        | "published"
        | "applications_open"
        | "selection_in_progress"
        | "in_progress"
        | "review_pending"
        | "completed"
        | "cancelled"
      campaign_task_type:
        | "instagram_feed_post"
        | "instagram_reel"
        | "instagram_story"
        | "tiktok_video"
        | "youtube_video"
        | "youtube_short"
        | "facebook_post"
        | "facebook_share"
        | "comment"
        | "like"
        | "share_post"
        | "follow"
        | "product_review"
        | "ugc"
        | "custom"
      campaign_type:
        | "product_launch"
        | "product_review"
        | "brand_awareness"
        | "event_promotion"
      creator_gender: "female" | "male" | "non_binary"
      ledger_entry_type:
        | "mock_deposit"
        | "campaign_funding_debit"
        | "campaign_funding_reserve"
        | "platform_fee"
      ledger_transaction_kind: "test_deposit" | "campaign_funding"
      notification_email_status: "pending" | "sent" | "failed" | "skipped"
      notification_type:
        | "application_received"
        | "application_selected"
        | "campaign_published"
        | "task_submitted"
        | "task_approved"
        | "task_rejected"
        | "payout_ready"
        | "payout_released"
      payment_transaction_status:
        | "pending"
        | "processing"
        | "succeeded"
        | "failed"
        | "cancelled"
      platform_role: "admin"
      proof_url_requirement: "required" | "optional" | "none"
      review_decision: "approved" | "rejected"
      social_account_status: "connected" | "disconnected"
      social_connection_method: "manual" | "oauth"
      social_platform: "instagram" | "tiktok" | "facebook" | "youtube"
      social_verification_status: "unverified" | "verified"
      wallet_account_kind:
        | "user_wallet"
        | "campaign_reserve"
        | "platform_revenue"
        | "provider_clearing"
      workspace_role: "advertiser" | "influencer"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {
      application_status: ["pending", "shortlisted", "selected", "rejected"],
      assignment_status: [
        "in_progress",
        "submitted",
        "revision_requested",
        "approved",
        "rejected",
        "expired",
        "payout_pending",
        "paid",
      ],
      campaign_funding_status: ["succeeded"],
      campaign_status: [
        "draft",
        "funding_required",
        "published",
        "applications_open",
        "selection_in_progress",
        "in_progress",
        "review_pending",
        "completed",
        "cancelled",
      ],
      campaign_task_type: [
        "instagram_feed_post",
        "instagram_reel",
        "instagram_story",
        "tiktok_video",
        "youtube_video",
        "youtube_short",
        "facebook_post",
        "facebook_share",
        "comment",
        "like",
        "share_post",
        "follow",
        "product_review",
        "ugc",
        "custom",
      ],
      campaign_type: [
        "product_launch",
        "product_review",
        "brand_awareness",
        "event_promotion",
      ],
      creator_gender: ["female", "male", "non_binary"],
      ledger_entry_type: [
        "mock_deposit",
        "campaign_funding_debit",
        "campaign_funding_reserve",
        "platform_fee",
      ],
      ledger_transaction_kind: ["test_deposit", "campaign_funding"],
      notification_email_status: ["pending", "sent", "failed", "skipped"],
      notification_type: [
        "application_received",
        "application_selected",
        "campaign_published",
        "task_submitted",
        "task_approved",
        "task_rejected",
        "payout_ready",
        "payout_released",
      ],
      payment_transaction_status: [
        "pending",
        "processing",
        "succeeded",
        "failed",
        "cancelled",
      ],
      platform_role: ["admin"],
      proof_url_requirement: ["required", "optional", "none"],
      review_decision: ["approved", "rejected"],
      social_account_status: ["connected", "disconnected"],
      social_connection_method: ["manual", "oauth"],
      social_platform: ["instagram", "tiktok", "facebook", "youtube"],
      social_verification_status: ["unverified", "verified"],
      wallet_account_kind: [
        "user_wallet",
        "campaign_reserve",
        "platform_revenue",
        "provider_clearing",
      ],
      workspace_role: ["advertiser", "influencer"],
    },
  },
} as const

